### ISSUE TITLE
the choice of --peak  

### ISSUE THREAD

**Issue by zhoudreames** [arangrhie/merfin#10]
I have two fully-phased  haploid  assembly of a diploid  specices  ,but I only want to polishing one of the two fully-phased  haploid genome,How should I choose the parameter “--peak” ，is haploid peak  value （43.3）or double of haploid_peak value（86.6）?
![image](https://user-images.githubusercontent.com/54714639/128593362-b78968c5-fe82-4b87-896c-61eb15b62c3e.png)

**Comment by arangrhie** [comment]
Hi @zhoudreames,

I'd say provide both haplotype assemblies and provide 43.3. If you only like to polish one haplotype, you could either provide vcf from one haplotype, or drop the filtered vcf from the other haplotype afterwards.

Merfin works best if the assembly matches the kmer spectrum as much as possible. Leaving one haplotype assembly out could cause potential haplotype switching.

Arang

**Comment by zhoudreames** [comment]
thanks~
