### ISSUE TITLE
Polish_genome

### ISSUE THREAD

**Issue by yao-chenxin** [arangrhie/merfin#15]
Hi, author:
      I want to polish the assembled genome and then get consensus FASTA, using Merfin. I now have FastA files and Illumina Reads FastQ files; How do I get a VCF file？Is it possible to use GATK to map FASTQ reads to the self-assembled genome FASTA?
     Look forward to hearing from you, thanks！
     With best wishes.

**Comment by arangrhie** [comment]
Hello @yao-chenxin , sorry for the very delayed reply.
Yes, you could use GATK or DeepVariant. Up to you.
I assume the assembly wasn't generated from Illumina reads though?

Best,
Arang
