### ISSUE TITLE
the usage and meaning of the plot in complele human genome article

### ISSUE THREAD

**Issue by zhoudreames** [arangrhie/merfin#7]
![image](https://user-images.githubusercontent.com/54714639/125286403-581a3980-e34e-11eb-96e9-70b361cb198d.png)
in your article,I am very interested in this plot,but i dont know how to draw the plot,and  what's means of the shape of the point and the color of point ? could you help me?thanks

**Comment by arangrhie** [comment]
Hi @zhoudreames ,

See this part: https://github.com/arangrhie/merfin#assess-collapses-and-duplications
Our manuscript describing this in more details will be available soon on bioRxiv. Stay tuned!

**Comment by zhoudreames** [comment]
> Hi @zhoudreames ,
> 
> See this part: https://github.com/arangrhie/merfin#assess-collapses-and-duplications
> Our manuscript describing this in more details will be available soon on bioRxiv. Stay tuned!

thanks ~
