### ISSUE TITLE
merfin doesnt respect -threads option

### ISSUE THREAD

**Issue by bredeson** [arangrhie/merfin#8]
Hi!

FYI, I'm running `merfin -dump -threads 8` at the moment, and it is currently running the `meryl count` step on the genome sequence fasta with 16 threads.  Is this a bug?

Best,
Jessen

**Comment by bredeson** [comment]
Ah, and the `-hist` function does this as well.

**Comment by arangrhie** [comment]
@brianwalenz could you take a look?

**Comment by brianwalenz** [comment]
It looks like the threads parameter doesn't propagate to the meryl subprocess.  A quick workaround is to set environment variable OMP_NUM_THREADS to what you want.

The code has been updated to fix this, too.

**Comment by bredeson** [comment]
Also with `-polish` as well.

Thanks for the tip!
